---

#- hosts: nodes
#  gather_facts: false
#  serial: 1
#  tasks:
#  - include_role:
#       name: vm_power
#    vars:
#      vm_state: 'powered_off'
- hosts: nodes:lb
  gather_facts: false
  serial: 7
  tasks:
  - include_role:
       name: remove_vm

- hosts: nodes:lb
  gather_facts: false
  serial: 7
  tasks:
  - include_role:
       name: clear_known_hosts

- hosts: localhost
  gather_facts: false
  tasks:
  - include_tasks: "include/removerecordsddns.yml"
